LOCAL_PATH := $(call my-dir)

PRIVATE_LOCAL_CFLAGS := -O2 -g -W -Wall		\
			-Wno-error=unused-parameter	\
			-DSO_RXQ_OVFL=40
#			-DPF_CAN=29
#			-DAF_CAN=PF_CAN

#
# canlib
#

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := lib.c canframelen.c
LOCAL_MODULE := libcan
LOCAL_C_INCLUDES := $(LOCAL_PATH)/include/
LOCAL_CFLAGS := $(PRIVATE_LOCAL_CFLAGS)
#LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_PATH  := $(TARGET_OUT_EXECUTABLES)
#LOCAL_MODULE_PATH  := $(LOCAL_PATH)/bin/

include $(BUILD_STATIC_LIBRARY)

#
# cansend
#

include $(CLEAR_VARS)

#LOCAL_MODULE_TARGET_ARCH := arm
LOCAL_SRC_FILES := cansend.c
LOCAL_MODULE := cansend
LOCAL_MODULE_TAGS := optional
LOCAL_STATIC_LIBRARIES := libcan
LOCAL_C_INCLUDES := $(LOCAL_PATH)/include/
LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_CFLAGS := $(PRIVATE_LOCAL_CFLAGS)
#LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_PATH  := $(TARGET_OUT_EXECUTABLES)
#LOCAL_MODULE_PATH  := $(LOCAL_PATH)/bin/

include $(BUILD_EXECUTABLE)

#
# candump
#

include $(CLEAR_VARS)

LOCAL_SRC_FILES := candump.c
LOCAL_MODULE := candump
LOCAL_MODULE_TAGS := optional
LOCAL_STATIC_LIBRARIES := libcan
LOCAL_C_INCLUDES := $(LOCAL_PATH)/include/
LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_CFLAGS := $(PRIVATE_LOCAL_CFLAGS)
#LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_PATH  := $(TARGET_OUT_EXECUTABLES)

include $(BUILD_EXECUTABLE)

#
# calc-bit-timing
#

include $(CLEAR_VARS)

#LOCAL_MODULE_TARGET_ARCH := arm
LOCAL_SRC_FILES := calc-bit-timing/can-calc-bit-timing.c
LOCAL_MODULE := cancalbt
LOCAL_MODULE_TAGS := optional
LOCAL_STATIC_LIBRARIES := libcan
LOCAL_C_INCLUDES := $(LOCAL_PATH)/include/
LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_CFLAGS := $(PRIVATE_LOCAL_CFLAGS)
#LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_PATH  := $(TARGET_OUT_EXECUTABLES)

include $(BUILD_EXECUTABLE)


